dbt_k8_demo:
  outputs:
    #this profile for exec with docker
    devDockerK8:
      type: bigquery
      dataset: dgt_govil_dbt_stg
      fixed_retries: 1
      location: europe-west3
      method: oauth
      priority: interactive
      project: govilgil
      threads: 5
      timeout_seconds: 300
      impersonate_service_account: dbt-user@govilgil.iam.gserviceaccount.com

    #this profile for exec local pc with service-account
    DevServiceAccount:
      type: bigquery
      method: service-account
      project: govilgil
      dataset: dgt_govil_dbt_stg
      threads: 1
      keyfile: 'C:\Users\gilc\.dbt\keyfile.json'
      timeout_seconds: 300
      priority: interactive
      retries: 1

  target: DevServiceAccount