dbt_k8_demo:
  outputs:
    default:
      type: bigquery
      dataset: dbt_k8_demo
      fixed_retries: 1
      location: europe-west2
      method: oauth
      priority: interactive
      project: rocketech-de-pgcp-sandbox
      threads: 5
      timeout_seconds: 300
      impersonate_service_account: dbt-user@rocketech-de-pgcp-sandbox.iam.gserviceaccount.com
