dbt_k8_demo:
  outputs:
    #this profile for exec with docker
    devDockerK8:
      type: bigquery
      dataset: dgt_govil_dbt_stg
      fixed_retries: 1
      location: europe-west3
      method: oauth
      priority: interactive
      project: govilgil
      threads: 5
      timeout_seconds: 300
      impersonate_service_account: dbt-user@govilgil.iam.gserviceaccount.com
    #this profile for exec local pc with service-account
    DevServiceAccount:
      type: bigquery
      method: service-account
      project: govilgil
      dataset: dgt_govil_dbt_stg
      threads: 1
      keyfile: 'C:\Users\gilc\.dbt\keyfile_DevServiceAccount.json'
      timeout_seconds: 300
      priority: interactive
      retries: 1
    TestServiceAccount:
      type: bigquery
      method: service-account
      project: dgt-gcp-egov-test-govilbi-0
      dataset: dgt_govil_dbt_stg
      threads: 1
      keyfile: 'C:\Users\gilc\.dbt\keyfile_TestServiceAccount.json'
      timeout_seconds: 300
      priority: interactive
      retries: 1
    TestDockerK8:
      type: bigquery
      dataset: dgt_govil_dbt_stg
      fixed_retries: 1
      location: europe-west3
      method: oauth
      priority: interactive
      project: dgt-gcp-egov-test-govilbi-0
      threads: 5
      timeout_seconds: 300
      impersonate_service_account: dbt-user@dgt-gcp-egov-test-govilbi-0.gserviceaccount.com
  target: TestDockerK8